---
name: weekly-github-packages
on:
  schedule:
    - cron: '0 0 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      platforms:
        description: build platforms, coma separated. linux/amd64,linux/arm64
        required: true
        default: linux/amd64
        type: string
env:
  REGISTRY_NAME: ghcr.io
  IMAGE_NAME: pkg-kamailio-docker
  REGISTRY_IMAGE: kamailio/pkg-kamailio-docker
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
    strategy:
      matrix:
        dist:
          - bullseye
          - bookworm
          - sid
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_NAME }}/${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{ github.ref_name }}-${{ matrix.dist }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.description=image with all required dependences
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ matrix.dist }}"
          platforms: ${{ github.event.inputs.platforms }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
